### PR TITLE
docs: add link to `react-query-native-devtools`

### PR DESCRIPTION
**Pull request by bgaleotti**
Ref.: #7

### CODE REVIEW

**Comment by tannerlinsley** [comment]
This is cool! Does it use these dev tools and integrate them into RQ somehow?

**Comment by bgaleotti** [comment]
No, it just provides a [Flipper](https://fbflipper.com/) plugin and a connector to hook into it.

You can see it working [here](https://streamable.com/388ueb).

**Comment by tannerlinsley** [comment]
Oh this is interesting!

**Pull request merged**
