### PR TITLE
fix: query stale state

### PR DESCRIPTION
**Pull request by boschni**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Did you test this?

**Comment by boschni** [comment]
Unfortunately I couldn’t find a method in the repo to test it. Could you provide some guidance on how to test it? The MR is to fix the issue that queries always show as fresh

**Comment by thebuilder** [comment]
Getting a `q.isStale is not a function` error when trying to open the dev tools, after upgrading to this version.

- react-query-devtools@2.4.6
- react-query@2.12.1

**Comment by thebuilder** [comment]
Reverting the version fixes the issue.

**Comment by boschni** [comment]
Created a PR to make the changes backwards compatible: https://github.com/tannerlinsley/react-query-devtools/pull/64

**Pull request merged**
