### PR TITLE
add style props and default z-index

### LINKED ISSUE #10: Style props and z-index on ReactQueryDevtools
Hi!

The `ReactQueryDevtools` component has a fixed position, but no z-index. Certain elements of a user's app may be displayed on top of the devtools. The same applies to the two buttons (open and close).

I can open a PR that sets `zIndex: '99999'` on all three elements, unless you want to do it differently.

Thanks for publishing this library!

### PR DESCRIPTION
**Pull request by tibotiber**
Closes #10 

Hi Tanner, I've tested this locally and it seems to work well. Let me know if there are any changes you'd like me to make. Thanks!

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Looks good to me

**Comment by tannerlinsley** [comment]
I think it would be cool to just support an object of props, that way people could add className and onClick handlers, etc.

**Comment by tibotiber** [comment]
I'm not sure I fully grasp what you mean, would you mind providing an example?

**Comment by tannerlinsley** [comment]
So instead of `panelStyle`, do `panelProps`:

```js
export function ReactQueryDevtools({
  initialIsOpen,
  { style: panelStyle = {}, ...panelProps } = {},
}) {

  return (
    <ReactQueryDevtoolsPanel
      ref={panelRef}
      ...{panelProps}
      style={{
        position: 'fixed',
        bottom: '0',
        right: '0',
        zIndex: '99999',
        width: '100%',
        height: '500px',
        maxHeight: '50%',
        boxShadow: '0 0 20px rgba(0,0,0,.3)',
        borderTop: `1px solid ${theme.gray}`,
        ...panelStyle,
      }}
    />
  )
}
```

**Comment by tibotiber** [comment]
Oh right, gotcha. Will push that in the hour.

**Comment by tibotiber** [comment]
Just pushed, this is indeed more flexible, great suggestion Tanner 👍.

**Comment by tannerlinsley** [comment]
I’ll cut a release in the morning

**Comment by tibotiber** [comment]
Hi Tanner, friendly ping in case that's gone out of mind.

**Comment by tannerlinsley** [comment]
Released! Sorry for the delay.

**Comment by tibotiber** [comment]
No problem, thanks!

**Pull request merged**
